### ISSUE TITLE
Use stadiums, not ellipses for state variables 

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#10]
_From @ugurdogrusoz on June 14, 2016 6:37_

The new (draft) version of SBGN PD 2.0 uses stadiums for state variables instead of ellipses.

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#135_

**Comment by mrsfy** [comment]
_From @ugurdogrusoz on June 16, 2016 11:45_

Let's make sure state variables and units of information boxes use the same font size.

**Comment by mrsfy** [comment]
Stadiums can be drawn by roundrectangle shapes of cytoscape. And to make it look like a [stadium](http://www.sbgn.org/images/1/1b/SBGN5.5-PDWhatsNext.pdf) I set radius parameter to **15**. I can change it by your feedback.
Font sizes for both units of info and state are already `height/1.5` and `height `depends on size of node.

The following is a reference for version updates of cytoscape.js:

Actually I couldn't find it reasonable (espacially for our usage) why` drawRoundRectanglePath` function has radius parameter as it does not use it anywhere in function but hardcode it. 

Not that `getRoundRectangleRadius` function just returns `Math.min( width / 4, height / 4, 8 );` (min of 3 parameters)

**-Change-**
In `drawRoundRectanglePath` function,
`cornerRadius = math.getRoundRectangleRadius( width, height );`
to
`cornerRadius = radius ? radius : math.getRoundRectangleRadius( width, height )`
**-Change-**


Anyway `drawRoundRectanglePath` was not using radius parameter but now it is. Thus, there is a consequence:
unit of information's radius parameter was set to 10 but was getting it from `getRoundRectangleRadius` but now it sets to exactly 10. I can change it back to old one by just removing these parameters.

**Comment by mrsfy** [comment]
Done in viewer, too. 
Commit: dff1003dabf11ce142ec5d92dda52aabbf9d9dcd

**Comment by mrsfy** [comment]
Seems fine now.

**Comment by ugurdogrusoz** [comment]
I think default font size increased for some reason.
