### ISSUE TITLE
Source/sink and logic symbols connection don't behave as expected

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/chise.js#102]
Source/sink cannot be connected in any way, should be able to connect to process.
Logic symbols can have other edges than logic arcs.

**Comment by royludo** [comment]
solved in iVis-at-Bilkent/chise.js@05a8d27b0685e64a518fe6f962423857467cc377
The source/sink/empty set now accepts edges according to specifications. Logic operators can now have output modulation edges.

**Comment by ugurdogrusoz** [comment]
Great thanks!
