### ISSUE TITLE
Weird behavior with 2 edges between same nodes

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/chise.js#104]
When you have 2 edges between the same 2 nodes, and both edges haven't been touched (no bend point used), then when you want to add a bend point to one edge, they kind of merge and get locked together.

Weirder thing: if the distance between the 2 nodes is large, you can correctly edit the bend point and have a normal behavior IF you click and place your bend point very close to one of the node. When clicking in the middle of the edge to place the bend point, the weird behavior happens.

**Comment by ugurdogrusoz** [comment]
Looks like a bug in the associated extension: https://github.com/iVis-at-Bilkent/cytoscape.js-edge-bend-editing/issues/11
Closing this
