### ISSUE TITLE
Node style reset upon inclusion in a compound/compartment

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/chise.js#105]
All nodes (compartments and compounds also) have their ~~border color~~_(doesn't change the border color)_, fill color and border width completely reset when they are included into other nodes (cmd/ctrl+drag). It seems to also affect the font properties, but not the font size.

**Comment by royludo** [comment]
Also, using cmd+click instead of cmd+drag to include something resets the style of the destination compound, but also of all the elements inside this compound. (but not the border color)

**Comment by royludo** [comment]
@ugurdogrusoz the problem with changing parents with cmd+drag is solved. But the cmd+click behavior is still buggy.

**Comment by royludo** [comment]
@metincansiper Better description of the problem: 
Just using ctrl/cmd + click on a compound, without anything selected, detaches it from its parent (and also changes paddings)

**Comment by metincansiper** [comment]
The problem seems to be solved now (Solved at chise level).

**Comment by ugurdogrusoz** [comment]
@royludo please verify and close if OK
