### ISSUE TITLE
Expand-collapse layout problem

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#106]
Looks like the specialized layout on expand-collapse (especially expanding a collapsed node) was somehow broken (for the past couple of days at the least). Try to expand and collapse compartments in the default diagram and you'll see what I mean.

**Comment by metincansiper** [comment]
@ugurdogrusoz It seems that this problem is caused by cose-bilkent extension. The problem does not appear when we use cose-bilkent v1.3.8. However, in later versions we have this problem.

**Comment by metincansiper** [comment]
It seems that this issue was mainly caused by expand-collapse extension. I fixed the problem there now it seems to be working.
