### ISSUE TITLE
Node connectivity in PD

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#109]
http://journal.imbio.de/article.php?aid=263

Page 41 of the above document has a table for which edges can connect to which nodes. Please make sure we correctly allow edges.

**Comment by royludo** [comment]
I did some overhaul of the edge validation. I included tables describing node connectivity so it's easier to change it in the future. It will avoid going into the code directly. I used both the link you provided and the more recent 2.0 version of the specs. But I found the last version really bad at providing clear connectivity constraints, unlike 1.3.
