### ISSUE TITLE
Moving a process in its entirety

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#11]
Moving nodes connected to a process as a process moves (moving a process in its entirety) might be useful. This could be implemented in two different ways:
- use the a extension?
- when the user clicks and holds (or double clicks) on a process, select its immediate neighbors so they can be moved together as a group. 
  In any case, we should make sure this doesn't break the animation that takes place during layout, expand, etc.

**Comment by matthiaskoenig** [comment]
This can be easily achieved by making a multiple selection, i.e. selecting the neighboring nodes manually.

**Comment by matthiaskoenig** [comment]
I just found there is a select -> neighbors already which solves this issue

**Comment by ugurdogrusoz** [comment]
That's highlight, not select Matthias. In any case, we'd like to make it easier, more convenient for the user.

**Comment by ugurdogrusoz** [comment]
Let's do this as follows:
- in the view-utilities extension, when a node is left-clicked and held (for a second or two, defined by an option) we apply the specified function to figure out what to do in such a case
- at the application level (SBGNViz and ChiSE), we should define that function to 
    o select the neighbors of the process when the clicked node is a process.
    o if the clicked node is not a process, then select all processes (and their neighbors) connected to this node (basically all processes that this node is involved in are selected).

**Comment by hasanbalci** [comment]
I solved the issue as mentioned in the above comment, but user should first taphold the node to select the desired neighbors and in a separate action move the selected nodes. Multiple selection with taphold is added to the view-utilities extension as a feature and it is applied to both SBGNViz and ChiSE sample apps for process-based selection.

**Comment by ugurdogrusoz** [comment]
doing this with regular left-click creates a confusion for selecting to align nodes. can we perhaps do this on a modifier key (Ctrl, Shift or Command) plus left-click and hold? see related code for transferring nodes in and out of compounds during drag.

**Comment by hasanbalci** [comment]
Now, multiple selection is done with Shift+(left-click and hold) to avoid confusion.
