### ISSUE TITLE
Context menus for nodes, edges, and background

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#12]
_From @ugurdogrusoz on June 16, 2016 11:36_

Let's add context menus (not too shiny as cxtmenu extension but something simpler) for nodes, edges, and background. These menus should have functionality that might be commonly used per node, per edge or per map. BioGene dialog that opens up on right-click should go to the context menu of nodes of type macromolecule. Expand/collapse can go to compound nodes.

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#137_

Let's talk about details first.

**Comment by ugurdogrusoz** [comment]
Node: Delete (deletes are simple)
  Expanded Node: Collapse
  Collapsed Node: Expand
Edge: Delete, Add Bend Point
  Bend: Remove Bend Point
Core: Delete Selected, Perform Layout, Hide Selected, Show All

BioGene Properties go to the inspector as discussed.

**Comment by ugurdogrusoz** [comment]
Some changes:
- Core: Add "Properties..."
- Order menu items in a pop-up menu in the same order as they appear in the menu (File menu items before Edit, etc.)
- Remove -> Delete (Remove Bend Point -> Delete Bend Point)
- Move bend point related items to the beginning of the edge/bend point popups

Some problems:
- Right click still triggers BioGene properties as a pop-up?
- Bio Gene Info -> BioGene Properties (in bold, same font size as Macromolecule Properties)
- Let's decrease the font size of the inspector property names (Label, Width, etc.) to be the same as the one for BioGene
- I don't see any reason for horizontal scrollbar to pop up but it does (as the vertical one pops up?)
- I am not too fond of expand/collapse icon for BioGene :)

**Comment by metincansiper** [comment]
I made the desired changes as described in this issue and we discussed in person.
