### ISSUE TITLE
Document saveAsSVG

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#120]
PNG and JPG exports are document but this one is missing.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  I think you meant to add the documentation in sbgnviz documentation. because PNG and JPG documentation is sbgnviz and its readme file not in chise.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh you're right, thanks!
