### ISSUE TITLE
Replace gulp & browserify with webpack

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/chise.js#124]
Newer node versions are not compatible with gulp v3. Therefore, let's replace gulp operations with webpack and npm scripts just as we do with other repositories in the organisation. Let's also change the entry point in package.json from "src/index.js" to "chise.js".

**Comment by msalihaltun** [comment]
I tested some functionality for integration with Newt, it seemed okay but we should continue testing.

**Comment by hasanbalci** [comment]
For now, there seems no problem, so I'm closing.
