### ISSUE TITLE
Change node dimensions from inspector

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#14]
_From @ugurdogrusoz on June 16, 2016 11:42_

We should display node width and height (both integers) in the inspector and allow editing. We should have a checkbox to lock/unlock aspect ratio. Note that this should not be displayed for compound nodes since their geometry is based on their children. We should talk about whether to keep the center or the upper left corner fixed on dimension changes. Make sure this is part of multiple object selection as well (i.e. support changing dimensions of multiple nodes)

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#139_

**Comment by mrsfy** [comment]
_From @metincansiper on June 21, 2016 12:33_

I have added the desired functionalities as described. I considered the special cases for compound nodes, collapsed nodes and processes. I implemented this operation as a part of multiple object inspection.

**Comment by mrsfy** [comment]
_From @ugurdogrusoz on July 13, 2016 9:7_

Can we move the lock icon so that it aligns with the center of the w and h fields (middle of the two, a little - a few pixes - to the right) ?

**Comment by metincansiper** [comment]
Here is the new look of inspector 

![inspector](https://cloud.githubusercontent.com/assets/6534865/16951718/df589a74-4dce-11e6-9a13-c510f476d188.PNG)
