### ISSUE TITLE
Decrease default dimensions of processes

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#15]
_From @ugurdogrusoz on June 16, 2016 11:47_

Processes should be created to be much smaller by default (about 40 percent of what dimensions are now). In general default node dimensions for new nodes should be similar to those in the samples.

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#141_

**Comment by mrsfy** [comment]
Just updated default dimensions of new processes (including dissociation and association)

**Comment by ugurdogrusoz** [comment]
We should also increase the dimensions of the following;
(2 x current width): macromolecule, nucleic acid feature, phenotype, unspecified entity, perturbing agent
(2 x current width & 2 x current height): molecular complex, compartment

**Comment by ugurdogrusoz** [comment]
Dimensions are fine but we somehow lost ability to change dimensions from the inspector?! Related to this commit?
