### ISSUE TITLE
Expose some more parameters as options

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#16]
_From @ugurdogrusoz on June 17, 2016 7:37_

Expose the new cose-bilkent options in Layout Properties

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#142_

**Comment by metincansiper** [comment]
I exposed new cose-bilkent options and commited the changes. The following is a new screenshot from layout properties dialog.

![layout-properties](https://cloud.githubusercontent.com/assets/6534865/16952589/7ddb036e-4dd2-11e6-89ab-dff0003d608e.PNG)

Shall I make the same changes in viewer too if there is no problem with this?

**Comment by ugurdogrusoz** [comment]
Please make the following changes:
- move the new options after Gravity (before Number of Iterations)
- Gravity Range Factor -> Gravity Range
- Compound Gravity Constant -> Compound Gravity
- Gravity Range Factor -> Compound Gravity Range

**Comment by metincansiper** [comment]
The following is the new look of layout properties dialog

![layout-properties](https://cloud.githubusercontent.com/assets/6534865/16980236/bbad7e24-4e6d-11e6-8fa5-5fcb5a07aff7.PNG)

**Comment by ugurdogrusoz** [comment]
Great! Can we also decrease the spacing (half of what it is now?) between options so that the dialog is not this high?

**Comment by metincansiper** [comment]
I decreased the spacing between the options. I made similar changes in other dialogs too ('File > Properties' and'View > Grid...') and reflected them to SBGNViz as well.

**Comment by ugurdogrusoz** [comment]
Looks great! One last thing: "Query > PC > Paths Between..." (missing dots). Please commit all changes to viewer as well.

**Comment by metincansiper** [comment]
I added the missing dots. All changes are commited to viewer as well.
