### ISSUE TITLE
Arbitrary number of info boxes controllable by user

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#17]
_From @ugurdogrusoz on June 17, 2016 7:59_

We need to find a way to create an arbitrary number of info boxes that can be controlled (created, edited, and moved) by the user

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#144_

**Comment by ugurdogrusoz** [comment]
This is long term, closing for now
