### ISSUE TITLE
Logical operators

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#19]
_From @fdurupinar on June 21, 2016 20:46_

Targets of logical arcs should be allowed to be logical operators. 

From the current sbgn specs:
Origin: Any EPN (Section 2.4) or logical operator (Section 2.10).
Target: Any logical operator (Section 2.10).

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#146_

**Comment by metincansiper** [comment]
I think that this was required to be handled in 'https://github.com/iVis-at-Bilkent/sbgnviz-js/issues/79'. However, I realized that previosuly multimers were not regarded as EPN's by mistake. I have fixed it now. I infer by the issue above that 'unspecified entity', 'simple chemical', 'macromolecule', 'nucleic acid feature', 'complex' and their multimers are EPN's. Is there any problem with my isEPN check. And is there still something wrong about this issue?

**Comment by fdurupinar** [comment]
My concern is about whether the targets of logic arcs can be logic operators or not. Currently, we can't define an operation such as (a AND b) OR ( c OR d) with an edge between AND and OR operators.

**Comment by ugurdogrusoz** [comment]
The original issue iVis-at-Bilkent/sbgnviz-js#79 was missing the fact that a logical arc can be between two logical operators, not just between an EPN and a logical operator. Let's please add this as a valid interaction.

**Comment by metincansiper** [comment]
I added the missing valid interaction.
