### ISSUE TITLE
Synchronous XMLHttpRequest Deprecation

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#21]
_From @teheavy on June 24, 2016 17:7_

Hi there,

Another warning:
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.
from sbgnml-to-json-converter.js Line 8

Please fix, thanks!
Fred

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#148_

**Comment by ugurdogrusoz** [comment]
@teheavy could you confirm it's fixed?
