### ISSUE TITLE
Better label support

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#24]
_From @ugurdogrusoz on July 14, 2016 11:11_

Currently each node has a label (e.g. gene symbol) and some info boxes (units of information and state variables). In addition, tags defined in PD notation can be used to annotate map objects. However, a more general support for labels (labels associated with nodes, edges or the map itself) would be useful. The labels should be either text or an image!

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#152_

**Comment by ugurdogrusoz** [comment]
Let's close this for now since it's long term!
