### ISSUE TITLE
Expand-collapse and bend-editing not fully compatible

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/chise.js#28]
When we try to collapse an edge, having bend points, we were getting an error. Currently we are removing bend-points of edges before a node is being collapsed to avoid this bug.

Also, adding bend points to meta edges is problematic.

**Comment by metincansiper** [comment]
It seems that this issue is dependant on 'https://github.com/cytoscape/cytoscape.js/issues/1487'

**Comment by metincansiper** [comment]
@ugurdogrusoz It seems that we get rid of this bug now. Shall we give up removing bend-points of edges before a node is being collapsed (I as wrote in the definition of the issue, currently we were doing it to avoid this bug).

**Comment by ugurdogrusoz** [comment]
I think so (similar to expand, where bendpoints are maintained)

**Comment by metincansiper** [comment]
I deleted the code segement which was removing bend-points of edges before a node is being collapsed.
