### ISSUE TITLE
Tool name change

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#29]
Please change the tool name as follows:
- html page title (SBGNViz.js -> Chisio SBGN Editor)
- upper left tile at menubar (SBGNViz.js -> Chisio SBGN Editor)
- Help > About (SBGNViz.js Editor version 1.0 -> Chisio SBGN Editor version 1.0)
- Help > About (.../iVis-at-Bilkent/sbgnviz-js -> .../iVis-at-Bilkent/chise.js)

**Comment by mrsfy** [comment]
I commited changes above.
