### ISSUE TITLE
Persisting node/edge properties not required by SBGN-ML

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#3]
Some node and edge properties available in SBGNViz are not actually required by SBGN-ML (e.g. node color). We should persist such properties as well in SBGN-ML similar to other SGBN tools (so we can exchange such properties as well).

**Comment by mrsfy** [comment]
_From @ugurdogrusoz on October 14, 2015 16:6_

Maybe we can use this:
http://www.sbgn.org/LibSBGN/SBGN-ML_Extensions
Here is a complete example: http://svn.code.sf.net/p/libsbgn/code/trunk/test-files/PD/neuronal_muscle_signalling_color.sbgn

**Comment by ugurdogrusoz** [comment]
Maybe we can use this:
http://www.sbgn.org/LibSBGN/SBGN-ML_Extensions
Here is a complete example: http://svn.code.sf.net/p/libsbgn/code/trunk/test-files/PD/neuronal_muscle_signalling_color.sbgn

**Comment by ugurdogrusoz** [comment]
In addition, we probably want to let the user annotate nodes/edges with custom data (e,g, associate a URL or pubmed ID with an edge). This would go to the Properties tab (need to discuss UI for this) and should be persisted along with other style, etc. properties of nodes/edges in extended SBGNML.

**Comment by ugurdogrusoz** [comment]
Also see: https://bitbucket.org/vtoure/sbgn-extension

**Comment by ugurdogrusoz** [comment]
Can we consider this done?
