### ISSUE TITLE
Dialog improvement

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#35]
In all dialogs, we should change Save to Apply and NOT close the window upon clicking this button. The dialog should be closed only when X is clicked. This applies to all dialogs, including
- File > Properties
- View > Grid
- Layout > Layout Properties
In the grid dialog, we have the following problems:
- For both Grid Size and Guideline Tolerance, we can enter invalid values that change the previous valid values, which is incorrect behavior.

**Comment by ugurdogrusoz** [comment]
Let's please make all dialogs modal (not able to do other things while the dialog is open).

**Comment by ugurdogrusoz** [comment]
Valid ranges in dialogs:
  Properties: Compound Padding [0-100] integer
  Grid: Grid Size [5-infinity) integer, Guideline Tolerance [0-infinity) double
  Query: Length Limit [1-infinity) integer
  Layout Properties:
    Node Repulsion [0,infinity) double
    Node Overlap doesn't exist in cose-bilkent, remove this!
    Ideal Edge Length [5,infinity) double
    Edge Elasticity [0,infinity) double
    Nesting Factor [0,infinity) double
    Gravity [0,infinity) double
    Gravity Range [0,infinity) double
    Compound Gravity [0,infinity) double
    Compound Gravity Range [0,infinity) double
    Number of Iterations [0,infinity) integer
    Tiling {Vertical, Horizontal} Padding [0,infinity) integer

**Comment by metincansiper** [comment]
- I made the dialogs modal and defined valid ranges as described. 
- In integer fields users just can enter '-' sign and numbers. 
- In float fields they can enter '.' character as well. 
- They can paste any text they want to the text fields, but upon value change (by enter key or clicking some empty field) the values in textboxes are validated or converted to valid values.

**Comment by ugurdogrusoz** [comment]
Nice, thanks!

**Comment by ugurdogrusoz** [comment]
Can we transfer these improvements (where applicable) to the viewer now?

**Comment by metincansiper** [comment]
I transfered these improvements to the viewer (where applicable).
