### ISSUE TITLE
Grid and guides lost on load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#36]
If you load a graph, you lose the grid and the guidelines; they no longer work! The bug might be in the related extension...

**Comment by mrsfy** [comment]
It seems working now.
Related commits: https://github.com/iVis-at-Bilkent/cytoscape.js-grid-guide/commit/6fe4bfed49584f9ddfc9c920ed4ae88299cf2892 and 8d815a180acaa578ed2a5107f6aaddfa7f42d937
