### ISSUE TITLE
Highlights

### ISSUE THREAD

**Issue by fdurupinar** [iVis-at-Bilkent/chise.js#37]
When "highlight neighbors" is called after "highlight processes", the processes of the selected element remain highlighted.

**Comment by ugurdogrusoz** [comment]
The current implementation is taking the union of what's currently highlighted with what is being highlighted.

**Comment by fdurupinar** [comment]
Then, we could use check boxes to indicate what is being highlighted. I.e.. processes, neighbors, both or none.

**Comment by ugurdogrusoz** [comment]
I am not sure I understand. Where would the check boxes go?

**Comment by fdurupinar** [comment]
I mean menu-> highlight,  where the highlight neighbors and processes are
selected. It doesn't have to be checkboxes, just something to indicate what
is being highlighted at the moment.

**Comment by ugurdogrusoz** [comment]
Highlighting will be redesigned anyway. Currently it's not very intuitive.
