### ISSUE TITLE
Resize through new extension

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#38]
Use the new node-resize extension for resizing nodes. I would use the orange that we use for selection for grapples (and gray for bounding box?), and bounding rectangle and a very tight padding (not touching the node). Also we should no longer color the border of nodes in selection color since selection is now signified by grapples!
Let's keep in mind that 
- some nodes aren't allowed to be resized, and
- some nodes are only allowed resizing keeping aspect ratio.

**Comment by mrsfy** [comment]
ChiSE now uses node-resize extension. And also the extension is now capable of desired features. Can you please specify which node types will be resized only by fixed aspect ratio and which node types with no resizing at all?

**Comment by ugurdogrusoz** [comment]
Nodes that aren't allowed a resize modifying aspect ratio:
- All process nodes (all under Edit > Add Node > Process), 
- Source & Sink
- All logical operators (AND, OR, and NOT)
Nodes that aren't allowed to be resized:
- Complexes
- Compartments

**Comment by ugurdogrusoz** [comment]
Stylistic issues:
- Nodes should no longer change border color upon selection
- Bounding box padding should be zero
- Resize should be undoable
- Border of the bounding rectangle should be dashed and black/dark gray
- Grapples should be orange (same color we use currently for selection)

**Comment by mrsfy** [comment]
May you check it now?

**Comment by ugurdogrusoz** [comment]
Issues that I see with node resize:
- bounding rectangle is a little off (to the right and bottom, it's a little shy)
- grapples are a little too small (hard to grab)
- as you're resizing a compartment, the node is filled with selection color (as if you are dragging that node)
- enabled grapples look a bit smaller than disabled ones (should be the same), maybe it's because the enabled grapples don't have borders?
- can we change the bounding rectangle's borders to dotted lines (similar to yEd's)?
- resize feels awfully slow on my laptop (will check on my desktop tomorrow).
- looks like we lost Ctrl + drag for transferring nodes to and from compounds.

**Comment by mrsfy** [comment]
Now updated for desired features. Can you please give feedback?
I optimized resizing as possible. However, cytoscape.js renders labels (because of both font sizing and trimming like Ca.. instead of Ca+2) slow and when width is too low and high is too high it crashes due to labels. (I removed labels and it seems very okey, and also cytoscape docs says that "Drawing labels is expensive".) As we are thinking to improve the label system and currently optimized node-resize seems almost fine, it would be better to wait for new label system.

**Comment by ugurdogrusoz** [comment]
Performance is much better.
Transfer functionality is back but we lost the specialized cursor for this operation (Ctrl-drag).
All other customization issues are solved, thanks.

**Comment by mrsfy** [comment]
It should be fixed now.
