### ISSUE TITLE
Cannot load this model

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#4]
_From @ugurdogrusoz on October 14, 2015 16:16_

This model imported from Reactome wont load! Can we find out why not? I changed the file extension so github issue tracker can attach it.
[391160.sbgn.txt](https://github.com/PathwayCommons/sbgnviz-js/files/13368/391160.sbgn.txt)

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#72_

**Comment by mrsfy** [comment]
_From @metincansiper on October 15, 2015 12:30_

The reason why it cannot be loaded is that the class of some nodes in this file is "annotation" which is not handled in sbgnviz.

**Comment by mrsfy** [comment]
_From @ugurdogrusoz on October 15, 2015 15:9_

Can we change our reader to "skip" such unrecognized classes?

**Comment by mrsfy** [comment]
_From @metincansiper on October 20, 2015 12:7_

Is skipping these classes means that when an element has one of these classes drawing it as a normal element(an element with no specific sbgnclass)?

**Comment by mrsfy** [comment]
_From @ugurdogrusoz on October 20, 2015 13:32_

Can't we just "ignore" them? "annotation" must be inside a glyph or arch, a property of a node or an edge that SBGNViz would not understand or care about. We should just skip such unrecognized elements.

**Comment by mrsfy** [comment]
_From @cannin on October 20, 2015 15:6_

Can you draw them as shown below? I think there are several glyphs that I do not think you are supporting. Ideally, you'd have them all, but in the meantime, can you put a simple placeholder, so that people at least know something was there and what it was supposed to be?

<img width="193" alt="screen shot 2015-10-20 at 10 57 42 am" src="https://cloud.githubusercontent.com/assets/790284/10611346/acef51e0-7719-11e5-8609-678f43b517a1.png">

**Comment by mrsfy** [comment]
_From @ugurdogrusoz on October 20, 2015 15:8_

I am confused Augustin. Are these "annotation"s actually units of information?

**Comment by mrsfy** [comment]
_From @cannin on October 21, 2015 19:42_

The proposed solution is a hack. While I think SBGNViz should support all the SBGN glyphs, I understand there can be resource limitations in implementing everything. I would rather see a default visualization of an unknown glyph instead of it disappearing from the diagram completely. The suggested rectangle would hopefully be a very simple way of doing the default representation of an unknown glyph.

**Comment by mrsfy** [comment]
_From @metincansiper on October 23, 2015 6:24_

Just ignored the unrecognized classes at least for now.

**Comment by ugurdogrusoz** [comment]
glyph annotations will be supported in persistence in chise at some point; a separate issue
