### ISSUE TITLE
Convenient bend point editing

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#44]
We can make bend point editing easier / more convenient if following are supported:
- [3] Ability to select a specific bend point (as opposed to or in addition to selecting the whole edge with bend points) and using Delete key to delete that bend point,
- [2] Ability to click anywhere on the edge to introduce and relocate a bendpoint by dragging,
- [1] If a bend point is released (during drag) "near" the line from the previous bend point to the next one (these neighboring bend points could be edge clipping points in case there is no such bend point), the bend point should be deleted.

**Comment by metincansiper** [comment]
I have added the functionality for [1] and [2] to edge-bend-editing extension. I think that it would be better if we discuss in person before I start to implement [3].

**Comment by ugurdogrusoz** [comment]
Perfect! Let's talk about [3], maybe we won't do it at all.

**Comment by ugurdogrusoz** [comment]
Let's leave it like this for now. I confirm it working on the viewer as well.
