### ISSUE TITLE
Auto panning on moving a node out of canvas bounds

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#46]
When the user drags a node towards the edge of the canvas, can we pan automatically (at a constant slow pace) and let the user drag the node further outward?

**Comment by metincansiper** [comment]
To do this I created a Cytoscape.js extension file and included it in ChiSE. If it is prefered we can create an extension repository for this and I can publish this as a Cytoscape.js extension with minimal effort.

**Comment by ugurdogrusoz** [comment]
Great, lets create an extention and publish it. What should we name it? Cytoscape.js-auto-pan-on-canvas-bounds?

**Comment by metincansiper** [comment]
I think that this name sounds nice.

**Comment by metincansiper** [comment]
I think that I do not have permission to create repository under iVis-at-Bilkent once you created it I can publish the extension. And also currently this extension has no options and methods. I think that it can have the following options and methods.

// Options
{
   enabled: true, // Whether the extension is enabled 
   selector: 'node' // Which elements will be affected by this extension
}

// Methods
.enable() // enable the extension
.disable() // disable the extension

How about this ones (I am not sure whether the selector option is useful) and do you have any further suggestions on this?

**Comment by ugurdogrusoz** [comment]
I think the proposed interface is fine including the selector. I created a repo for it.

**Comment by metincansiper** [comment]
Ok, thanks.

**Comment by metincansiper** [comment]
I have published the extension and used it in ChiSE.
