### ISSUE TITLE
Ask whether to save on New

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#47]
When the user creates a new map using File > New, we should confirm whether or not the user wants to save the current map first (Do you want to save any change(s) to the map? Save, Don't Save, Cancel).

**Comment by metincansiper** [comment]
When user creates a new map using 'File > New' or its toolbar icon the desired dialog pops up. I made the dialog modal like the other dialogs in ChiSE. 

Dialog looks like the following:

![prompt-save-dialog](https://cloud.githubusercontent.com/assets/6534865/17462984/80cd3c2a-5cc5-11e6-94b5-5b5f9a5b55cf.PNG)

**Comment by ugurdogrusoz** [comment]
Great! Can we just resize this dialog to be a bit wider so that the question fits in one line (instead of two)?

**Comment by metincansiper** [comment]
Here is the new look of dialog after making the desired change:

![capture](https://cloud.githubusercontent.com/assets/6534865/17581332/cecd042e-5fad-11e6-825f-492df5205ff8.PNG)
