### ISSUE TITLE
Highlight bugs

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#49]
- Edges, info box labels, etc. are not "ghosted" (still visible) as expected from this feature.
- Doesn't work on maps other than the default sample diagram.

**Comment by metincansiper** [comment]
I changed the highlighted and unhighlighted elements style as we disscussed in person. The following is the new view when some elements are highlighted. I used the yellow as highlight color. If needed I can change it to any desired color.

![capture](https://cloud.githubusercontent.com/assets/6534865/17663341/a3b1a020-62f4-11e6-9a44-51bc48ed1787.PNG)

**Comment by ugurdogrusoz** [comment]
How come edge arrow heads are not painted upon highlight? Also yellow is too hard to see by itself; can we try turquoise / cyan?

**Comment by metincansiper** [comment]
I increased the width of highlighted edges and border-width of highlighted nodes as we discussed. I applied the changes to the viewer as well.
