### ISSUE TITLE
Cannot create nodes

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#54]
When in node creation mode, clicking in the root results in panning not creation of nodes.

**Comment by metincansiper** [comment]
This bug seems to be fixed now. I re-deployed ChiSE after fixing this bug.

**Comment by ugurdogrusoz** [comment]
Yes I can create nodes now. I dont know if this is related at all but how come compartment and complex node sizes are so small? At some point, we made their default sizes much bigger than this!
