### ISSUE TITLE
Ordering of properties dialogs and use of tab

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#58]
One should be able to use "tab" key to move between various properties in all dialogs including various settings and the inspector.

**Comment by ugurdogrusoz** [comment]
This should be done after @metincansiper finishes his refactoring (please talk to him).

**Comment by ugurdogrusoz** [comment]
Let's do this at SBGNViz level (sample-app repo unstable branch) only for now. Please talk to Metin first.

**Comment by metincansiper** [comment]
It seems that html tabindex attribute (http://stackoverflow.com/questions/4112289/what-is-the-html-tabindex-attribute) will work here.

**Comment by ugurdogrusoz** [comment]
Great, thanks!
