### ISSUE TITLE
Submaps and terminals

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#6]
_From @ugurdogrusoz on December 17, 2015 14:50_

Currently we do not support these node types (mainly since we do not like the way they are represented and drawn in SBGN-PD). We should discuss this and think about how they could be supported.

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#101_

**Comment by mrsfy** [comment]
_From @ugurdogrusoz on June 14, 2016 7:21_

With the new specs (SBGN PD 2.0), looks like it's easier to implement these. Basically, one can select a number of related processes and define a submap over these. A new submap node representing the submap is created, and can be collapsed and expanded just like complexes or compartments. This introduces a new (3rd) type of a compound node.

**Comment by ugurdogrusoz** [comment]
Let's discuss first

**Comment by ugurdogrusoz** [comment]
Please use this image as an icon in the toolbar, etc. for submap:
https://drive.google.com/file/d/0B9ApNnKlfgcHbDFjakNGVV80T1k/view?usp=sharing

**Comment by kinimesi** [comment]
@ugurdogrusoz This image looks like a rounded rectangle in Safari. Can you double check it (open the SVG file with Safari)?
![a](https://user-images.githubusercontent.com/7281872/28189738-ee92dcda-682f-11e7-8b37-12a6ec9d4ebf.png)

**Comment by ugurdogrusoz** [comment]
Both Safari and Chrome, I see a regular rectangle

**Comment by ugurdogrusoz** [comment]
Now we have a basic submap implementation, not compliant with SBGN but simple as it should be.
