### ISSUE TITLE
Additional padding for complexes with info boxes

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#61]
We should detect complexes with info boxes which overlap with the members of the complex since paddings are not enough, and increase the padding internally.

**Comment by royludo** [comment]
@ugurdogrusoz I don't fully understand. The info boxes don't overlap, they just touch the complex members. Do I still increase the padding when info boxes are there ? Overlap with the complex name has been taken into account, though.

**Comment by ugurdogrusoz** [comment]
See the myosin-actin-ATP and myosin-actin complexes in muscle cytosol in default map
