### ISSUE TITLE
Sample app not found

### ISSUE THREAD

**Issue by matthiaskoenig** [iVis-at-Bilkent/chise.js#63]
Hi all,
I just wanted to start the sample app via the `here` link in the README, but get a
404 not found for
http://www.cs.bilkent.edu.tr/%7Eivis/ChiSE.js_daily/sample-app/

Where is the sample app?
M

**Comment by ugurdogrusoz** [comment]
Sorry for outdated link; please use this one: http://www.cs.bilkent.edu.tr/~ivis/ChiSE.js/sample-app/
