### ISSUE TITLE
Process nodes on compartment boundary not drawn

### ISSUE THREAD

**Issue by matthiaskoenig** [iVis-at-Bilkent/chise.js#64]
Hi all,
I have often processes layouted directly on the compartment borders in SBGN.
This are mainly transporter reactions which exchange between the inside and outside of the compartment and are located in the plasma membrane.

An example is attached.
[galactose_overview_v08.sbgn.zip](https://github.com/iVis-at-Bilkent/chise.js/files/495066/galactose_overview_v08.sbgn.zip)

In chise.js these processes are not drawn at the specified positions but outside of the compartment. It seems currently impossible to put processes directly on the compartment boundary.

The best 
Matthias

**Comment by ugurdogrusoz** [comment]
This is a side effect of #66. When it's resolved so will this.
