### ISSUE TITLE
Selecting multiple objects makes chise.js irresponsive

### ISSUE THREAD

**Issue by matthiaskoenig** [iVis-at-Bilkent/chise.js#65]
Hi all,
when trying to select multiple objects (~30) via Shift+mouse selection it takes very long (a few seconds). Firefox even complains about "the script stopped working". It is than impossible to work with the selection.

```
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://www.cs.bilkent.edu.tr/%…ild/dist/latest/ocanvas.min.js:12
```
I mainly want to select multiple objects and put them in a compartment at once.

Firefox 49, Ubuntu Linux 16.04

The best
Matthias

**Comment by ugurdogrusoz** [comment]
You're right there is a performance problem with the resize. This is to be fixed in the related extension: https://github.com/iVis-at-Bilkent/cytoscape.js-node-resize/issues/6. Thanks.
Regarding moving multiple nodes in and out of a compound, this is currently not possible but should be added: #67.

**Comment by ugurdogrusoz** [comment]
@matthiaskoenig #67 is now done and you can transfer multiple nodes in and out of compounds. For performance reasons we disabled resize of multiple nodes, so multiple object selection should be fast now. Please let us know if you still think it has performance issues.

**Comment by matthiaskoenig** [comment]
Thanks. Working now.
