### ISSUE TITLE
Transferring multiple nodes in and out of compounds

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#67]
One should be able to transfer multiple nodes into or out of a compound, not just a single one at a time.

**Comment by metincansiper** [comment]
What about the new positions of the transferred nodes? Previously the transferred node was located at the mouse release position.

**Comment by ugurdogrusoz** [comment]
Suppose there are 2 seleceted nodes nodes A and B. We click on and srart dragging A and leave inside the boundaries of compound C. We move A be the total drag amount. The same applies to B. So the relative positions of A and B should be the same after the transfer as they were initially.

**Comment by metincansiper** [comment]
I added this feature to ChiSE.
