### ISSUE TITLE
Arrow head sizes too small

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#7]
_From @ugurdogrusoz on January 7, 2016 16:23_

This was fixed in the past (please see this old issue #82 for the problem) but it's back to smaller sizes now.

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#105_

**Comment by metincansiper** [comment]
There is an open issue (https://github.com/cytoscape/cytoscape.js/issues/884) for this in Cytoscape.js.

**Comment by ugurdogrusoz** [comment]
Let's wait for cytoscape.js core for now

**Comment by ugurdogrusoz** [comment]
Cytoscape.js will have this in version 3.1

**Comment by ugurdogrusoz** [comment]
Should be done right after upgrade

**Comment by metincansiper** [comment]
@ugurdogrusoz Latest cytoscape.js provides us with this feature. They expose 'arrow-scale' style property of edges for this purpose.
The default value of the 'arrow-scale' is 1 and the arrow heads seems like the following with default behaviour:
![arrow-scale-1](https://cloud.githubusercontent.com/assets/6534865/25177259/e454f67c-2509-11e7-8619-e4038b5fb14c.PNG)
If we set 'arrow-scale' to1.5 we have the following result:
![arrow-scale-1-5](https://cloud.githubusercontent.com/assets/6534865/25177280/f8e6a144-2509-11e7-9cce-c2a0d92455da.PNG)
If we set it to 2 we get the following result:
![arrow-scale-2](https://cloud.githubusercontent.com/assets/6534865/25177299/0acaf608-250a-11e7-9148-87d8ce0c5368.PNG)
Which value  should be used for 'arrow-scale' style property?

**Comment by ugurdogrusoz** [comment]
1.5 looks good I think

**Comment by metincansiper** [comment]
Okey I set it as 1.5

**Comment by amazein** [comment]
After we changed the default font size and related shape sizes, the view was excellent. I think now the arrowheads are too big, for example catalysis arrowhead is almost the size of the process glyph.

**Comment by ugurdogrusoz** [comment]
Right, looks like we exaggerated a bit. Decreased to 1.25 with https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/9275e8fefabfb413e500122dbae2222a7d5c9cb8.
