### ISSUE TITLE
Add Compound for Selected broken

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#70]
Both Add {Complex,Compartment} for Selected are broken

**Comment by ugurdogrusoz** [comment]
Transfer in general seems to be broken

**Comment by metincansiper** [comment]
The problem related to Add {Complex,Compartment} for Selected and the other problems related to transfer seems to be solved now.

**Comment by ugurdogrusoz** [comment]
There is a minor problem though (I don't know if this was previously there). If you select two nodes and first apply "Add Selected to Complex" followed by "Add Selected to Compartment" we end up with an invalid structure where the complex includes a compartment, which shouldn't be allowed!

**Comment by metincansiper** [comment]
I missed this case. I handled it now and it seems to be working as expected.
