### ISSUE TITLE
Some operations will not work with loaded/queried models

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#73]
Same problem with the viewer: https://github.com/iVis-at-Bilkent/sbgnviz-js/issues/164

**Comment by metincansiper** [comment]
The problem seems to be solved now in the extension level.

**Comment by ugurdogrusoz** [comment]
Looks fine. Please transfer fixes to the viewer, and close the issue.

**Comment by metincansiper** [comment]
@ugurdogrusoz  This fix was done in extension level. I suppose that the problem in viewer is solved with the same fix. I checked it and it seems that it is working as expected in viewer as well. I am closing the issue.
