### ISSUE TITLE
Auto form parent-child relation on load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#75]
Currently we figure out whether or not there is a parent child relation between a node and another node which is a compound (complex or compartment). This should be an option under File > Properties... ("Infer Parent-Child Relations on Load").

**Comment by ugurdogrusoz** [comment]
@royludo Can you confirm that even if a node is inside the boundaries of another node (a compound one), file loader will not set the compound node as this node's parent unless SBGNML file specifies a compartment reference?

**Comment by royludo** [comment]
@ugurdogrusoz I confirm.
But I don't remember removing any code related to that. So, the parts doing this must still be there and having this behavior back shouldn't be too difficult I think.

**Comment by ugurdogrusoz** [comment]
OK, let's have a flag under General Map Properties with name "Infer Parent-Child Relations on Load" (could go after Enable Ports as the last option of this section), which is true by default, and figures out the compartment reference of a node upon load (as it used to). If this flag is off, current behavior is to continue. Here is an example (what is expected and what we see on load are different due to missing compartment references but could be inferred on load; here Nucleus should be inside Cytosol):
- https://github.com/sbgn/libsbgn/blob/master/example-files/transforming_growth_factor_beta_signaling_pathway.png
- https://github.com/sbgn/libsbgn/blob/master/example-files/transforming_growth_factor_beta_signaling_pathway.sbgn

**Comment by ugurdogrusoz** [comment]
@hasanbalci any idea why this is still open, we already have a flag for this?

**Comment by hasanbalci** [comment]
@ugurdogrusoz  I think this issue is outdated, you can close it.
