### ISSUE TITLE
Port support for processes and logic operators

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#77]
We should implement ports for processes and logical operators and make them an option under File > Properties. Perhaps we could allow them to rotate as well (l-r, r-l, t-b, b-t). Since static layout doesn't support them, we can disable ports on static layout.

**Comment by metincansiper** [comment]
I added this feature to newt (By adding the needed functionality to sbgnviz and chise and using them in newt).

**Comment by ugurdogrusoz** [comment]
Great job; here are improvements to finalize the support:
https://docs.google.com/document/d/1wkoNCquXlQdrqnTiurizhJVcOtjN79wxEvPPjJNn5ag/edit?usp=sharing

**Comment by metincansiper** [comment]
@ugurdogrusoz I made the improvements requested in the document except from two of them.

One of the improvements which is not done yet is the following "Logical operators with ports don’t have the text middle aligned (text is closer to the top of the shape)".
For this one I see that the vertical and horizontal allignment for the nodes with ports are already "center".

The other improvements which is not done yet is that "Edges are not attaced to the ports properly when the orientation of the ports are just changed. However, if you move the related node though they get attached properly". 

You can test the other improvements.

**Comment by ugurdogrusoz** [comment]
Well done! Regarding remaining issues: 1) alignment is no big deal 2) this is a more general problem of refreshing/redrawing in Cytoscape.js core; so let's consider it independent from this issue.

I tested it and remaining minor issues are at the top of the same document.

**Comment by metincansiper** [comment]
@ugurdogrusoz I handled the remaining issues.

**Comment by ugurdogrusoz** [comment]
All are fine except no. 6 (modulation arcs getting attached to a port when port orientation is first changed to none and then back to say l-r)

**Comment by metincansiper** [comment]
@ugurdogrusoz no. 6 seems to be solved now.
