### ISSUE TITLE
Multi-selection in compounds not working

### ISSUE THREAD

**Issue by matthiaskoenig** [iVis-at-Bilkent/chise.js#78]
The selection of multiple nodes in a compartment via
ctrl + shift + select 
is not working and only selecting the the compartment.
There should be a way to select multiple nodes in a compartment.

Also add the shortcut for multiple selection to 
ctrl + shift + select to Help -> Quick Help

**Comment by ugurdogrusoz** [comment]
Correct me if I am wrong, you'll be able to Ctrl (or Shift) + select within a compartment (or complex) to perform marquee (rectangle) selection, right? Currently when you do that the compartment (or complex) drag is started. I agree this would be nice and should be done at Cytoscape.js level.

**Comment by ugurdogrusoz** [comment]
@matthiaskoenig Box selection quick help addressed in a separate issue: https://github.com/iVis-at-Bilkent/newt/issues/8
Box selection inside a compound is implemented but problematic: https://github.com/cytoscape/cytoscape.js/issues/1583#issuecomment-285015425

**Comment by ugurdogrusoz** [comment]
Works fine now!
