### ISSUE TITLE
Node minimization/maximization should not trigger layout (compartment)

### ISSUE THREAD

**Issue by matthiaskoenig** [iVis-at-Bilkent/chise.js#79]
When minimzing node a layout is applied.
This destroys the manual layouts.
Applying minimization and maximization completely removes any manual layout information.

Automatic layouts should only be applied if selected by users via
Layout -> Perform Layout
This has the side effect of making minimization and maximization much faster.
-> just put the minimzed node in the center position of the maximized node (compartment)

**Comment by ugurdogrusoz** [comment]
Just disable File > Properties > Rearrange After Expand-Collapse if you don't want layout after expand or collapse.
