### ISSUE TITLE
Global, Class and Node visual properties

### ISSUE THREAD

**Issue by matthiaskoenig** [iVis-at-Bilkent/chise.js#81]
Currently, there is no way to change the Visual Properties globally or for classes of nodes, i.e.
- for all glyphs
- or for all Prosesses, for all Simple Chemicals, ...
- or for a selection of nodes

When creating the map one wants to change the style for classes of nodes at once.

When clicking 
'Set as Default for Process' this is only the Default for newly created Processes but not applied to already existing once in the graph.
=> This must be applied to all Processes, i.e include the existing once

For instance I would like to see the menu on the right for global Visual Properties, i.e
if no node is selected there is a
Glyph Visual Properties
with Label, Width, ...
which you can than make Default for Glyph, i.e. for all nodes in the network

The Defaults for more specific types like Simple Chemical are than taken from the glyph, but can be overwritten for the complete subclass.
This allows to
* define general Visual Properties once
* overwrite certain Properties for glyph classes like Simple Chemical
* overwrite for individual nodes

This provides an efficient mean to style the view without having to click every node and type the values.

**Comment by ugurdogrusoz** [comment]
Right click on a node and "Select Objects of This Type" and then apply your changes from the inspector.
