### ISSUE TITLE
Improving load performance

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#83]
https://github.com/iVis-at-Bilkent/sbgnviz-js/blob/unstable/src/utilities/sbgnml-to-json-converter.js

Above code has low performance for following reasons and can be improved as follows as per Max: 

The reason this JS is slow is because it's using jQuery to do traversals and searching and because there are several unneeded searches and traversals (some duplications, for example).  JS can generally parse XML just as fast as Java.  jQuery is not meant for proper XML, and it's not fast for traversals or searches.   jQuery should be removed and native APIs like [Element.querySelectorAll()](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll) should be used instead.  The existing converter is a great start, it just needs a little refactoring to make it faster.

**Comment by metincansiper** [comment]
I think that this is done by Dylan.
