### ISSUE TITLE
Meta edge style problem

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#84]
In the default diagram, collapse and then expand back one of the compartments. Upon undo, you'll see the meta edges to be very thick (as if they were highlighted).

**Comment by metincansiper** [comment]
The problem seems to be solved in extension level. Please see 'https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/issues/20'.

**Comment by ugurdogrusoz** [comment]
I just redeployed ChiSE, the problem is still there?

**Comment by ugurdogrusoz** [comment]
It turned out to be a cache problem, it is fixed.
