### ISSUE TITLE
Performance issue on node drag

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/chise.js#90]
Selecting and dragging several nodes or a compound node with several (20-30) children is slow. It gets really noticeable on an average laptop. Part of this issue comes from too frequent trigger calls with canvas reset through clearRect(). Origin:
 - some custom extensions to cytoscape are imported (cytoscape-edge-bend-editing, expand-collapse, node-resize and grid-guide)
 - each one adds a trigger that contains a clearRect() call to the cy.on('position') event handler or some other node moving event
 - the triggers pile up

As a result, the entire canvas is reset for each pixel moved, for each node moved, for each library. Regardless of any edge bend being edited or node being resized, for example.

**Comment by metincansiper** [comment]
@royludo I made performance improvements in some extensions including node-resize, expand-collapse, edge-bend-editing before you opened this issue as well (If you have this node drag problem even in small graphs you may not update these extensions in your build). However, after you opened this issue I missed some points which cause performance decrease especially on node drag in large graphs. 

Now I made some more performance improvements in extensions and redeployed chise with these improvements to here (http://www.cs.bilkent.edu.tr/~ivis/ChiSE_sample_app/). 

In an instance of chise I deactivated all extensions and compred the performance of it and the original chise which has the latest improvements in extensions on node drag. I see that the percieved performance in original chise is close to the percieved performance of the instance where the extensions are deactivated. However, the grid-guide extension creates a difference in percieved performance. If you want to have a better percieved performance on drag you can uncheck 'Show Alignment Guidelines' under "View < Grid".

What do you think about the new deployment here (http://www.cs.bilkent.edu.tr/~ivis/ChiSE_sample_app/). Is it still slow for you on drag (Please clean your cache before using chise in that link, sometimes we may have cache problems)?

**Comment by royludo** [comment]
I checked the new version and it is way better now, thanks.
