### ISSUE TITLE
Multi-line label support

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#91]
A user should be able to create labels with multiple lines. Cytoscape.js supports this, the question is how do we integrate it into interactive use? Using the Enter key (not the Return key) or Shift-Return? Please see how tools like Inkscape do it. Let's discuss before implementation.
Notice that labels can be created in two ways: 1) double click on a node 2) using the inspector (Properties tab on the right)

**Comment by ivanovaos** [comment]
Current combination for making a new line: shift+enter on the canvas and the same in inspector (property) panel; also works if someone adds manually \n. 

Further things for discussion: 
1) how to show new line in the inspector panel. Now it is '\n'
2) shall we add vertical slider for textarea (while editing) if there are many lines?

**Comment by ugurdogrusoz** [comment]
I think what we have implemented is fine as is. I am not sure what you mean by updating when label fields loses focus. Don't we already have this?
