### ISSUE TITLE
Zoom very slow when resize grapple are shown, on firefox only

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/chise.js#93]
Safari and Chrome are fine. Only happen when one node is selected and grapples appear. Dragging node is fine, only zoom is affected. Tested on the online sample app.

**Comment by royludo** [comment]
I can't replicate on another firefox on another pc, but I let it open for now. Will do further tests.

**Comment by ugurdogrusoz** [comment]
Please close if not reproducible

**Comment by royludo** [comment]
I've reproduced it. It's the scrolling device that is responsible somehow. It only happens with Apple magic mouse or trackpad devices (not necessarily Apple trackpads), and only with firefox. I can't imagine how to fix this...

**Comment by royludo** [comment]
I don't know what to do with this one...

**Comment by ugurdogrusoz** [comment]
Let's forget about this unless somebody complains about it again
