### ISSUE TITLE
Color schemes

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#96]
It'd be great to have a selection of color schemes (with one scheme being the default) for all nodes/edges/info boxes, etc. Please work with Alexander to choose a number of such schemes and integrate into the editor (under File > Properties for now).

**Comment by royludo** [comment]
Done partly in iVis-at-Bilkent/chise.js-sample-app@c249ccc0a27daf378280c1a9b4f3d24eee7977f9
Need to improve the color schemes themselves, info boxes are not colored.

**Comment by ugurdogrusoz** [comment]
We could also change the map background color in some schemes from white to some other color

**Comment by ugurdogrusoz** [comment]
This should be an undoable action. Please talk to @metincansiper as he needs to fix something before you can make this undoable.

**Comment by ugurdogrusoz** [comment]
Any particular reason that you are setting opacity values with different color schemes? Maybe we shouldn't set them at all?

**Comment by hasanbalci** [comment]
Currently, when a new node is added, it does not colored according to the previously selected color scheme.

**Comment by ugurdogrusoz** [comment]
Regarding the comment by @hasanbalci , maybe we can set the defaults (see the button at the end of the inspector) with the color scheme, so that newly created nodes/edges get the latest color scheme chosen.

**Comment by royludo** [comment]
@ugurdogrusoz if the opacity is not at maximum, the colors do not render the same, and the background color of a compound, for example, can interfere. As a general rule, I don't think there should be any transparency, or maybe just for compartments. For example, it makes mutlimers look different from any other map I've seen. I was looking to change this with default font and size from issue #97 

@hasanbalci indeed, the scheme should set the defaults for next nodes. Will work on that.

**Comment by royludo** [comment]
@hasanbalci should be resolved in  iVis-at-Bilkent/chise.js-sample-app@df2cbb33105d58ef462edf576bc5c97594b71fba

**Comment by ugurdogrusoz** [comment]
Regarding opacity, multimers are a different story. The current rendering for multimers is not ideal (this is one of the areas where we're hoping Cytoscape.js core will do something about). Compound nodes (compartment and complexes) should be transparent to some degree by default. Having no transparency at all is tricky since it has the potential for a node or an edge hiding behind another node. Transparency helps in such situations. I think we should avoid full opacity at least in most color schemes. I wouldn't change the default transparencies in #97.

**Comment by ugurdogrusoz** [comment]
Make sure to initialize titles ("Map color scheme" -> "Map Color Scheme") and increase width of dropdown box to fit scheme names

**Comment by royludo** [comment]
No more opacity, last comment issues fixed in  iVis-at-Bilkent/newt@b3a9cc754160a1a20d00e7a79e11de976a45dcea . I leave this open because there are still things to work on and discuss.

**Comment by ugurdogrusoz** [comment]
Undo doesn't undo defaults ("Set Default for ..." button in Properties)

**Comment by royludo** [comment]
Fixed in iVis-at-Bilkent/newt@a9d263cea61a1a499967e897eaa7f7761efcca37

**Comment by ugurdogrusoz** [comment]
I just noticed that change of color scheme doesn't apply to collapsed (nodes that become visible when a compound node is collapsed) or hidden nodes (nodes that become visible when a group of nodes are hidden through the View > Hide/Show menu)

**Comment by ugurdogrusoz** [comment]
I also noticed that Undo doesn't change the setting in Properties (should go back to previous Color Scheme)

**Comment by royludo** [comment]
Collapsed and hidden nodes are colored properly, menu setting behaves correctly with undo/redos.

I wanted to point out a problem with the current location of the color scheme setting.
 - currently, as this setting is part of the General menu, the color scheme is applied when the user hit the Save button. This happens even if the user didn't change the color scheme. Let's say he went into the menu to change some other values, then hit Save. Color scheme gets applied, and he may lose the style of some nodes defined previously.
 - imagine if we apply the color scheme only if the user changes it. It means that if he wants to reapply his color scheme for some reason (maybe to make his map more homogeneous after some style change), he won't be able to. He would need to change and apply another color scheme, and then apply his previous one.

This is due to color schemes being actions that are applied once, and immediately. Whereas other settings in the menus are just values being set, and that can be used later. We will need to think about it for the future.

**Comment by ugurdogrusoz** [comment]
That's a very good point @royludo. Should we perhaps move it to the view menu? We could also have it in the toolbar additionally with a dropdown box. What do you think?

**Comment by royludo** [comment]
@ugurdogrusoz yes, we could put it in the view menu and present the choices like the sample files. Maybe we can put a dropdown list in the toolbar temporarily, but I don't think it will be used so much that it deserves a place there, in the end.

**Comment by ugurdogrusoz** [comment]
Makes sense, let's just *move* this to View menu then (before "Grid and Guidelines..."). No need to put in the toolbar.

**Comment by ugurdogrusoz** [comment]
OK, let's also see if we can put this in a tab on the right as discussed. We could create a new tab for this or maybe incorporate into the existing Properties tab (this is a property of the map anyway), which is shown when no node or edge is selected (with a title: "Map Visual Properties").

**Comment by ugurdogrusoz** [comment]
Maybe we can rename existing Properties tab as "Object Properties" and the new general properties as "Map Properties"

**Comment by ugurdogrusoz** [comment]
I think it'd be great if we could allow users to define their own color schemes

**Comment by amazein** [comment]
User-defined colour scheme or several user-defined schemes would be great, especially if we make it easy for them. 

From experience, map developers rarely change default settings. Take a look at CellDesigner diagrams. Most simply use the default colours which are not nice (in my opinion).

The set prepared by Ludovic is good enough but could be improved. I would be happy to participate and work on that more as soon as we clearly see the options in the right-side panel.

Ugur, please decide on the name for the tab and let's move forward?

**Comment by ugurdogrusoz** [comment]
I included this discussion in the agenda for our next meeting. I think we're pretty much decided on the naming of the tabs. We just need to decide on the actual UI (I wasn't able to understand what Ludovic proposed fully).

**Comment by ugurdogrusoz** [comment]
Let's close this issue and handle improvements to the Color Scheme (e.g. user defined color scheme) in separate issues.
