### ISSUE TITLE
Default node font and dimensions

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#97]
Decrease the default node font size to 11 as well as their dimensions (macromolecules to 70x35, processes to 20x20, and others with a similar factor). Due to this change we need to decrease font sizes and dimensions for infoboxes (state variables and units of information) as well.

**Comment by amazein** [comment]
Would infoboxes have the same font size? Ideally, probably for later, the font size for infoboxes should be changeable too. As a default, it could be the same: 11. Or, alternatively, say, 11 for macromolecules, 10 or 9 for infoboxes.

**Comment by ugurdogrusoz** [comment]
Yes font size for infoboxes should decrease as well as stated in the issue. Inspection (and editing) of their style is not straightforward and will hopefully be implemented in upcoming releases.

**Comment by ugurdogrusoz** [comment]
Please address #92 as well

**Comment by royludo** [comment]
The defaults have been changed according to what was asked, except for a few things. I'll list the new defaults here:
- all font size to 11, 9 for state and info units. 
- macromolecule-like: 70x35
- simple chemical: 35x35
- process-like: 15x15
- logic operators and sink: 25x25
borders seem thicker now, but @amazein liked it.
I didn't notice any discrepancies related to #92

**Comment by ugurdogrusoz** [comment]
I think this changed made the overall look nicer. The border width got too thick however; we made a slight adjustment here:
simple node, complex, and edge width: 1.5 -> 1.25
compartment: 3.75 -> 3.25
