### ISSUE TITLE
Update problem for locked aspect ratio

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#98]
If you change the dimension of a node using the inspector (Properties dialog) when the aspect ratio is locked (explicitly by the user or implicitly as in processes), the change in the other dimension is not reflected to the inspector. For instance, if process dimensions are 30x30 and you change the width to 20, the drawing in the canvas is updated but the width in the inspector isn't.

**Comment by royludo** [comment]
solved in this commit: iVis-at-Bilkent/chise.js-sample-app@cd63e38dea48d39b8c667b5c050b268f0c0224b9
