### ISSUE TITLE
Unrelated guideline when viewport shifted by node movement

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/chise.js#99]
When the node is dragged outside of the current view and therefore viewport shifted, some unrelated guideline appears.  I think this is because the canvas that guidelines are drawn is not updated with the shift in viewport and guideline tries to align according to the previous rendered positions of nodes. An example case is as follows:

![guideline](https://cloud.githubusercontent.com/assets/22586369/23274222/88252ff4-fa0a-11e6-9ed8-0ef644535505.png)

**Comment by kinimesi** [comment]
Should be fixed now on ChiSE_daily. Can you verify and close?

**Comment by hasanbalci** [comment]
I think, it is solved except the guideline to the initial mouse position. It seems that initial mouse position is accepted as the rendered position, but I think it may be better if the initial mouse position is considered relative to the other nodes (model position). Because currently initial mouse position  becomes independent from the node's position when first clicked on it.
